### ISSUE TITLE
BEM as a way to avoid CSS collisions

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3450]
BEM is pattern of working in CSS to avoid collision of styles between elements. It is arguably the most common formalized CSS pattern used nowadays.

Here's a explanation: http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

More links: https://github.com/getbem/awesome-bem

Our apps could in fact use BEM **with** Bootstrap effectively, like this:

```html
                <ul class="chatter-autocomplete">
                    <template is="dom-repeat" items="{{model.FoundAttachment}}">
                        <li class="chatter-autocomplete__item">
                            <button type="button" class="btn btn-sm btn-link" onmousedown="++this.value;" value="{{item.Choose$::click}}">{{item.NameAndType}}</button>
                        </li>
                    </template>
                </ul>
```

The above is a replacement for https://github.com/StarcounterSamples/Chatter/blob/4ab372448a9cd31de13eec04e94c65c29066e599/wwwroot/Chatter/ViewModels/ChatGroupPage.html#L35-L41

```css
.chatter-autocomplete {
    display:block;
    background-color:white;
    box-shadow: 0 2px 6px 0 rgba(0, 0, 0, 0.37);
    list-style-type:none;
    padding:0px;
    margin:2px 0px;
    position:absolute;
}

.chatter-autocomplete__item {
    padding:0px;
}
```

https://github.com/StarcounterSamples/Chatter/blob/4ab372448a9cd31de13eec04e94c65c29066e599/wwwroot/Chatter/css/chatter.css#L1-L18

@miyconst, @tomalec, WDYT? If we all agree this is the way to go, let's gradually adapt all apps to it.
